language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm install
  - CI=false
  - npm run build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN 