language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - CI=false
  - npm run build
  - CI=true
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN 
  skip_cleanup: true